### ISSUE TITLE
Retrofit2 support?

### ISSUE THREAD

**Issue by edenman** [loggly/loggly-client#3]
Similar to https://github.com/tony19/timber-loggly/issues/13, it looks like Retrofit 2 support is on master here but hasn't been released.  Can you make a release?  Or lmk what else you'd like to do before cutting a release, and I can take a look?

**Comment by tony19** [comment]
@edenman Sorry for the delay. I'm currently trying to modernize the release with Gradle scripts in the [`wip/gradle-release` branch](https://github.com/loggly/loggly-client/tree/wip/gradle-release).

**Comment by tony19** [comment]
Addressed in a5bb0c433f4f581c2d5cae70695c8d3ceea61da6
